import 'package:cookie_store_app/models/category.dart';
import 'package:cookie_store_app/models/meal.dart';

const CATEGORY = const [
  Category(
    id: 'c1',
    title: 'Cookies',
  ),
  Category(
    id: 'c2',
    title: 'Cupcake',
  ),
  Category(
    id: 'c3',
    title: 'Ice Cream',
  ),
  // Category(
  //   id: 'c4',
  //   title: 'Ice',
  // ),
];

const MEALS = const [
  Meal(
    id: 'm1',
    category: 'c1',
    name: 'Cookie Cream',
    price: '5.99',
    imgPath: 'assets/images/cookie_cream2.png',
    description:
        'Cold, creamy ice cream sandwiched between delicious deluxe cookies. Pick your favorite deluxe cookies and ice cream flavor.',
    added: true,
    isFavorite: true,
  ),
  Meal(
    id: 'm2',
    category: 'c1',
    name: 'Cookie Mint',
    price: '3.99',
    imgPath: 'assets/images/cookie_mint2.png',
    description:
        'Cold, creamy ice cream sandwiched between delicious deluxe cookies of mint. Pick your favorite ice cream flavor.',
    added: false,
    isFavorite: false,
  ),
  Meal(
    id: 'm3',
    category: 'c1',
    name: 'Cookie Choco',
    price: '2.99',
    imgPath: 'assets/images/cookie_choco2.png',
    description: 'A delicious cookie of chocolate.',
    added: false,
    isFavorite: false,
  ),
  Meal(
    id: 'm4',
    category: 'c1',
    name: 'Cookie Classic',
    price: '1.99',
    imgPath: 'assets/images/cookie_classic2.png',
    description: 'A delicious cookie with chocolate drops.',
    added: false,
    isFavorite: true,
  ),
  Meal(
    id: 'm5',
    category: 'c2',
    name: 'Cupcake Chocolate and Coffee',
    price: '3.99',
    imgPath: 'assets/images/cupcake_choco_coffee.png',
    description: 'A delicious chocolate cupcake with coffee cream.',
    added: false,
    isFavorite: true,
  ),
  Meal(
    id: 'm6',
    category: 'c2',
    name: 'Cupcake Chocolate and Lemon',
    price: '3.99',
    imgPath: 'assets/images/cupcake_choco_lemon.png',
    description: 'A delicious chocolate cupcake with lemon mousse cream.',
    added: false,
    isFavorite: false,
  ),
  Meal(
    id: 'm7',
    category: 'c2',
    name: 'Cupcake Chocolate and Oreo',
    price: '5.99',
    imgPath: 'assets/images/cupcake_choco_oreo.png',
    description: 'A delicious chocolate cupcake with cream and oreo cookie.',
    added: false,
    isFavorite: true,
  ),
  Meal(
    id: 'm8',
    category: 'c2',
    name: 'Cupcake Red Velvet',
    price: '6.99',
    imgPath: 'assets/images/cupcake_redvelvet.png',
    description: 'A delicious cupcake red velvet with Ninho cream.',
    added: false,
    isFavorite: false,
  ),
  Meal(
    id: 'm9',
    category: 'c3',
    name: 'Ice Cream Blackberry and Chocolate',
    price: '13.99',
    imgPath: 'assets/images/ice_cream_blackberry_chocolate.png',
    description: 'A delicious Blackberry and Chocolate ice cream.',
    added: true,
    isFavorite: false,
  ),
  Meal(
    id: 'm10',
    category: 'c3',
    name: 'Ice Cream Caramel and Chocolate',
    price: '11.99',
    imgPath: 'assets/images/ice_cream_chocolate_caramel.png',
    description:
        'A delicious cream ice cream with Chocolate and Caramel coating.',
    added: false,
    isFavorite: true,
  ),
  Meal(
    id: 'm11',
    category: 'c3',
    name: 'Ice Cream Strawberry',
    price: '9.99',
    imgPath: 'assets/images/ice_cream_strawberry.png',
    description:
        'A delicious Strawberry cone ice cream. Choose your favorite flavor.',
    added: false,
    isFavorite: false,
  ),
  Meal(
    id: 'm12',
    category: 'c3',
    name: 'Ice Cream Tiramisu',
    price: '12.99',
    imgPath: 'assets/images/ice_cream_tiramisu.png',
    description:
        'A delicious Tiramisu cone ice cream. Choose your favorite flavor.',
    added: false,
    isFavorite: true,
  ),
  // Meal(
  //   id: 'm13',
  //   category: 'c4',
  //   name: 'Ice Cream Blackberry and Chocolate',
  //   price: '13.99',
  //   imgPath: 'assets/images/ice_cream_blackberry_chocolate.png',
  //   added: true,
  //   isFavorite: false,
  // ),
  // Meal(
  //   id: 'm14',
  //   category: 'c4',
  //   name: 'Ice Cream Caramel and Chocolate',
  //   price: '11.99',
  //   imgPath: 'assets/images/ice_cream_chocolate_caramel.png',
  //   added: false,
  //   isFavorite: true,
  // ),
  // Meal(
  //   id: 'm15',
  //   category: 'c4',
  //   name: 'Ice Cream Strawberry',
  //   price: '9.99',
  //   imgPath: 'assets/images/ice_cream_strawberry.png',
  //   added: false,
  //   isFavorite: false,
  // ),
  // Meal(
  //   id: 'm16',
  //   category: 'c4',
  //   name: 'Ice Cream Tiramisu',
  //   price: '12.99',
  //   imgPath: 'assets/images/ice_cream_tiramisu.png',
  //   added: false,
  //   isFavorite: true,
  // ),
];
